image: docker:18-git

services:
  - docker:18-dind

variables:
  DOCKER_TLS_CERTDIR: ""


stages:
  - build

build-backend:
  stage: build
  script:
    - docker build -t mcc/backend ./backend
    - docker run -d -p 8080:8080   mcc/backend 
