  image: ubuntu:18.04
  
  stages:
    - build

  build-backend:
    stage: build
    before_script:
      - apt-get update && apt-get install -y docker
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sudo sh get-docker.sh
    script:
      - docker build -t mcc/backend ./backend
      - docker run -p 8080:8080   mcc/backend 