package mcc.group14.apiclientapp.data

import java.io.Serializable

data class ProjectDetail(
    var name: String,
    var description: String,
    var project_type: String,
    var requester_email: String,
    var is_project_administrator: String,
    var team_members: String,

    var project_id: String? = null,
    var deadline: String? = null,
    // it is generated by be
    var creation_time: String? = null,
    var last_modified: String? = null,
    var badge: String? = null,
    var keywords: String? = null
    // TODO: add last_modified: String
) : Serializable {
    fun convertToUserProject(): UserProject{
        return UserProject(name = name, description = description, project_type = project_type,
            requester_email = requester_email, project_id = project_id, deadline = deadline,
            team_members = team_members, badge = badge, keywords = keywords, creation_time = creation_time, last_modified =last_modified)
    }
}